smtp:
  listen_addr: ":1069"
  domain: "server.feddatabase.com"
  tls:
    enabled: false
    cert_file: "certs/cert.pem"
    key_file: "certs/key.pem"
  auth:
    users:
      - username: "smsohag"
        password: "sohag999"
  max_message_size: 26214400  # 25 MB

delivery:
  workers: 5
  max_retries: 5
  retry_interval: "5m"
  connect_timeout: "30s"
  send_timeout: "5m"
  helo_name: "server.feddatabase.com"
  dkim:
    enabled: false
    selector: "default"
    private_key_file: "dkim/private.key"
    domain: "example.com"

queue:
  dir: "queue"

api:
  listen_addr: ":8068"
  auth_token: "change-this-secret-token"

admin:
  username: "admin"
  password: "admin123"      # change this!

web:
  listen_addr: ":8069"
  secret_key: "change-this-32-char-secret-key!!"

# Database: sqlite (default) or mysql
database:
  driver: "mysql"
  #path: "smtp-server.db"
  # MySQL (when driver: "mysql"):
  host: "localhost"
  port: 3306
  user: "mauticuser"
  password: "Marketing1"
  database: "mautic"
  charset: "utf8mb4"


logging:
  level: "info"
